version: '3.9'

services:
  julia:
    image: harlok13/julia:0.1

    env_file: .env

    restart: always

    depends_on:
      - db

  db:
    image: postgres:15.2

    environment:
      POSTGRES_USER: $(POSTGRES_USER)
      POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)
      POSTGRES_DB: $(POSTGRES_DB)

    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./data:/data
      - julia_db:/var/lib/postgresql/data

    restart: always

volumes:
  julia_db:


