"""Initial check

Revision ID: bf1d3bc9a740
Revises: 
Create Date: 2023-04-02 16:40:32.351685

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bf1d3bc9a740'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triggers_table')
    op.drop_table('books')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
                    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
                    sa.Column('user_nickname', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
                    sa.Column('admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False,
                              nullable=True),
                    sa.Column('register_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False,
                              nullable=True),
                    sa.Column('update_date', sa.DATE(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
                    sa.UniqueConstraint('username', name='users_username_key'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('books',
                    sa.Column('book_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
                    sa.Column('description', sa.TEXT(), server_default=sa.text("'description'::text"),
                              autoincrement=False, nullable=True),
                    sa.Column('reviews', sa.TEXT(), server_default=sa.text("'grandfather description'::text"),
                              autoincrement=False, nullable=True),
                    sa.Column('content', sa.TEXT(), server_default=sa.text("'soon'::text"), autoincrement=False,
                              nullable=True),
                    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.Column('cb_data', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('book_id', name='books_pkey')
                    )
    op.create_table('triggers_table',
                    sa.Column('trigger_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name_trigger', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('value_trigger', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='triggers_table_user_id_fkey'),
                    sa.PrimaryKeyConstraint('trigger_id', name='triggers_table_pkey')
                    )
    # ### end Alembic commands ###
